### PR TITLE
Filter out files without extension

### PR DESCRIPTION
**Pull request by bfenty**

### CODE REVIEW

**Review by gantoine — APPROVED** [review]

**Comment by bfenty** [comment]
Found that hidden files starting with a period and without a file extension also cause issues, so added some logic to filter them out as well.

**Comment by gantoine** [comment]
I don't think `max_ext_length` will work as we've come across valid extensions longer then 4 characters. If you're looking to filter hidden files check that the first char isn't a period.

**Comment by bfenty** [comment]
Ok, I'll rework it. That's a better solution.

**Review by gantoine — APPROVED** [review]
looks great, thanks for the fix!

**Pull request merged**
