### PR TITLE
Normalize rom names when parsing exact matches (remove diacritics & special characters)

### LINKED ISSUE #454: [Bug] Special characters awareness
Try to match the names by ignoring the special characters if no match is found, for example in this case the game was not found because the rom name contains a "-" instead of a "/" that of course it's an illegal character for file paths.

image

image

### PR DESCRIPTION
**Pull request by sondregronas**
Removes diacritics, special characters, accents and articles from rom names when comparing exact matches

Figured I'd just create a PR after all (See #680), might also resolve #454, at least when the rom's name is otherwise equivalent.

(Though this does nothing to the search term itself, so I'm not 100% sure if it solves #454)

### CODE REVIEW

**Comment by sondregronas** [comment]
Do you want me to update the PR to go into release instead?

**Comment by gantoine** [comment]
> Do you need me to update the PR to go into release instead?

No master is good, we merge master into release before each new version is released (including RCs)

**Comment by sondregronas** [comment]
@gantoine Done - sorry for the delay.

**Review by zurdi15 — APPROVED** [review]

**Comment by gantoine** [comment]
@sondregronas Sorry I think I misspoke, can you make your PR look exactly like #710 and re-open it to merge into our master branch instead? I want the work to be attributed to you as a contributor, and not have to close this PR.

**Pull request merged**
