### PR TITLE
Additional platform assets for Webrcade integration

### PR DESCRIPTION
**Pull request by Casuallynoted**
Pulled direct from the Webrcade repo (as per the attributions file located in the directory). Tbh, I do kind of prefer the thumbnail images that were originally in here vs the updated Webrcade equivalents but that's just my preference.

### CODE REVIEW

**Review by gantoine — APPROVED** [review]

**Comment by gantoine** [comment]
> Tbh, I do kind of prefer the thumbnail images that were originally in here

No reason we can't keep those, since we control the assets by having them in this repo we decide which ones to use. If you want to make any changes I'll leave this PR open for a day.

**Comment by Casuallynoted** [comment]
That sounds good to me! I'll go ahead and make some changes real quick and then we can probably close it!

**Comment by Casuallynoted** [comment]
Made changes, but going to quick test them on my local instance before I can confirm they're good to go

**Comment by Casuallynoted** [comment]
Ok, this looks good in use! I think this is ready to go :)

Some platforms are missing custom background images, but if I see that webrcade adds them to their default feed over time I'll gladly make prs to pull them over here (if they offered a template I'd also be happy to make them myself but atm they don't, might make an issue about that!)

**Review by gantoine — APPROVED** [review]

**Comment by gantoine** [comment]
@Casuallynoted this looks awesome, but can you re-open this PR against master?

**Comment by Casuallynoted** [comment]
Oh gosh absolutely! Let me get you set there one sec

**Pull request closed without merging**
