### PR TITLE
Populate homepage with platform cards and stats

### PR DESCRIPTION
**Pull request by GAntoine**
Populates the homepage with platform cards and basic stats about the library.

* Add `ipdb` for quick access to ipython debugger

### Screenshots

Screenshot 2023-05-13 at 2 42 13 PM

### CODE REVIEW

**Comment by zurdi15** [comment]
Oh dude this seems so cool! I'll test it and of course merging it, you are helping me so much, I appreciate that a lot!

**Comment by GAntoine** [comment]
Awesome, and feel free to tweak the CSS (padding, header, etc), I'm not super familiar with the CSS classes for vuetify.

**Comment by zurdi15** [comment]
imagen
imagen


I made some changes, what do you think?

**Comment by GAntoine** [comment]
Looks great with the slugs 👌🏼

**Pull request merged**
